apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongo-data
  name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-webapp
  name: fleetman-webapp
spec:
  type: NodePort
  ports:
    - name: "30080"
      port: 80
      targetPort: 80
      nodePort: 30080
      # port: 30080
      # targetPort: 80
  selector:
    io.kompose.service: fleetman-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-webapp
  name: fleetman-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: fleetman-webapp
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fleetman-webapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: fleetman-webapp
              topologyKey: kubernetes.io/hostname
      containers:
        - image: supinfo4kube/web-app:1.0.0
          name: fleetman-webapp
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-queue
  name: fleetman-queue
spec:
  # type: NodePort
  ports:
    - name: "8161"
      targetPort: 8161
      port: 8161
    #   nodePort: 8161
      # port: 8161
      # targetPort: 8161
    - name: "61616"
      port: 61616
      targetPort: 61616
      # nodePort: 61616
      # port: 61616
      # targetPort: 61616
  selector:
    io.kompose.service: fleetman-queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-queue
  name: fleetman-queue
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: fleetman-queue
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fleetman-queue
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: fleetman-queue
              topologyKey: kubernetes.io/hostname
      containers:
        - image: supinfo4kube/queue:1.0.1
          name: fleetman-queue
          ports:
            - containerPort: 8161
              protocol: TCP
            - containerPort: 61616
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-position-tracker
  name: fleetman-position-tracker
spec:
  type: NodePort
  ports:
    - name: "30010"
      port: 8080
      nodePort: 30010
      targetPort: 8080
      # port: 30010
      # targetPort: 8080
  selector:
    io.kompose.service: fleetman-position-tracker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-position-tracker
  name: fleetman-position-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: fleetman-position-tracker
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fleetman-position-tracker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: fleetman-position-tracker
              topologyKey: kubernetes.io/hostname
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
          image: supinfo4kube/position-tracker:1.0.1
          name: fleetman-position-tracker
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-position-simulator
  name: fleetman-position-simulator
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: fleetman-position-simulator
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fleetman-position-simulator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: fleetman-position-simulator
              topologyKey: kubernetes.io/hostname

      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
          image: supinfo4kube/position-simulator:1.0.1
          name: fleetman-position-simulator
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-mongodb
  name: fleetman-mongodb
spec:
  # type: NodePort
  ports:
    - name: "27017"
      # port: 27017
      # nodePort: 27017
      # targetPort: 27017
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: fleetman-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-mongodb
  name: fleetman-mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: fleetman-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fleetman-mongodb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: fleetman-mongodb
              topologyKey: kubernetes.io/hostname
      containers:
        - image: mongo:3.6.23
          name: fleetman-mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      restartPolicy: Always
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-api-gateway
  name: fleetman-api-gateway
spec:
  type: NodePort
  ports:
    - name: "30020"
      nodePort: 30020
      port: 8080
      targetPort: 8080
      # port: 30020
      # targetPort: 8080
  selector:
    io.kompose.service: fleetman-api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-api-gateway
  name: fleetman-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: fleetman-api-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fleetman-api-gateway
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: fleetman-api-gateway
              topologyKey: kubernetes.io/hostname
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
          image: supinfo4kube/api-gateway:1.0.1
          name: fleetman-api-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
