kubectl apply -f mongo-data-persistentvolumeclaim.yaml
kubectl apply -f fleetman-webapp-service.yaml
kubectl apply -f fleetman-webapp-deployment.yaml
kubectl apply -f fleetman-queue-service.yaml
kubectl apply -f fleetman-queue-deployment.yaml
kubectl apply -f fleetman-position-tracker-service.yaml
kubectl apply -f fleetman-position-tracker-deployment.yaml
kubectl apply -f fleetman-position-simulator-deployment.yaml
kubectl apply -f fleetman-mongodb-service.yaml
kubectl apply -f fleetman-mongodb-deployment.yaml
kubectl apply -f fleetman-api-gateway-service.yaml
kubectl apply -f fleetman-api-gateway-deployment.yaml