apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-position-tracker
  name: fleetman-position-tracker
spec:
  ports:
    - name: "30010"
      port: 30010
      targetPort: 8080
  selector:
    io.kompose.service: fleetman-position-tracker
