apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-api-gateway
  name: fleetman-api-gateway
spec:
  type: NodePort
  ports:
    - name: "30020"
      nodePort: 30020
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: fleetman-api-gateway
