apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-api-gateway
  name: fleetman-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: fleetman-api-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fleetman-api-gateway
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: fleetman-api-gateway
              topologyKey: kubernetes.io/hostname
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: local-microservice
          image: supinfo4kube/api-gateway:1.0.1
          name: fleetman-api-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
