apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-position-simulator
  name: fleetman-position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fleetman-position-simulator
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fleetman-position-simulator
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: local-microservice
          image: supinfo4kube/position-simulator:1.0.1
          name: fleetman-position-simulator
      restartPolicy: Always
