apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fleetman-queue
  name: fleetman-queue
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: fleetman-queue
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fleetman-queue
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: fleetman-queue
              topologyKey: kubernetes.io/hostname
      containers:
        - image: supinfo4kube/queue:1.0.1
          name: fleetman-queue
          ports:
            - containerPort: 8161
              protocol: TCP
            - containerPort: 61616
              protocol: TCP
      restartPolicy: Always